package com.jd.cho.rule.engine.dal.DO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rule_pack
 */
@Data
@SuperBuilder
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class RulePackDO extends BaseEntity {
    /**
     * Database Column Remarks:
     * 主键
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.id")
    private Long id;

    /**
     * Database Column Remarks:
     * 规则包编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.rule_pack_code")
    private String rulePackCode;

    /**
     * Database Column Remarks:
     * 规则包名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.rule_pack_name")
    private String rulePackName;

    /**
     * Database Column Remarks:
     * 规则包类型
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.rule_pack_type")
    private String rulePackType;

    /**
     * Database Column Remarks:
     * 规则调度策略
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.rule_arrange_strategy")
    private String ruleArrangeStrategy;

    /**
     * Database Column Remarks:
     * 版本号
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.version")
    private Integer version;

    /**
     * Database Column Remarks:
     * 是否最新版本（0:否，1:是）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.latest")
    private Integer latest;

    /**
     * Database Column Remarks:
     * 备注
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.remark")
    private String remark;

    /**
     * Database Column Remarks:
     * 状态（0:否，1:是）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.status")
    private Boolean status;

    /**
     * Database Column Remarks:
     * 规则包入参
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.pack_params")
    private String packParams;

    /**
     * Database Column Remarks:
     * 规则内容
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_pack.rule_content")
    private String ruleContent;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRulePackCode(String rulePackCode) {
        this.setRulePackCode(rulePackCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRulePackName(String rulePackName) {
        this.setRulePackName(rulePackName);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRulePackType(String rulePackType) {
        this.setRulePackType(rulePackType);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRuleArrangeStrategy(String ruleArrangeStrategy) {
        this.setRuleArrangeStrategy(ruleArrangeStrategy);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withVersion(Integer version) {
        this.setVersion(version);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withLatest(Integer latest) {
        this.setLatest(latest);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withPackParams(String packParams) {
        this.setPackParams(packParams);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_pack")
    public RulePackDO withRuleContent(String ruleContent) {
        this.setRuleContent(ruleContent);
        return this;
    }
}