package com.jd.cho.rule.engine.dal.DO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rule_def
 */
@Data
@SuperBuilder
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class RuleDefDO extends BaseEntity {
    /**
     * Database Column Remarks:
     * 主键
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.id")
    private Long id;

    /**
     * Database Column Remarks:
     * 优先级
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.priority")
    private Integer priority;

    /**
     * Database Column Remarks:
     * 规则条件
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_condition")
    private String ruleCondition;

    /**
     * Database Column Remarks:
     * 规则行为
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_action")
    private String ruleAction;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleCondition(String ruleCondition) {
        this.setRuleCondition(ruleCondition);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleAction(String ruleAction) {
        this.setRuleAction(ruleAction);
        return this;
    }
}