package com.jd.cho.rule.engine.dal.DO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rule_factor
 */
@Data
@SuperBuilder
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class RuleFactorDO extends BaseEntity {
    /**
     * Database Column Remarks:
     * 主键
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.id")
    private Long id;

    /**
     * Database Column Remarks:
     * 因子编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.factor_code")
    private String factorCode;

    /**
     * Database Column Remarks:
     * 因子名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.factor_name")
    private String factorName;

    /**
     * Database Column Remarks:
     * 分组编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.group_code")
    private String groupCode;

    /**
     * Database Column Remarks:
     * 因子类型（日期、数值、集合、布尔、文本）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.factor_type")
    private String factorType;

    /**
     * Database Column Remarks:
     * 常量类型（Input:输入，Enum:枚举，Script:脚本）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.constant_type")
    private String constantType;

    /**
     * Database Column Remarks:
     * 常量值
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.constant_value")
    private String constantValue;

    /**
     * Database Column Remarks:
     * 脚本参数
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.factor_script_param")
    private String factorScriptParam;

    /**
     * Database Column Remarks:
     * 备注
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.remark")
    private String remark;

    /**
     * Database Column Remarks:
     * 状态（0:否，1:是）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.status")
    private Boolean status;

    /**
     * Database Column Remarks:
     * 脚本代码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_factor.factor_script")
    private String factorScript;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withFactorCode(String factorCode) {
        this.setFactorCode(factorCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withFactorName(String factorName) {
        this.setFactorName(factorName);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withGroupCode(String groupCode) {
        this.setGroupCode(groupCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withFactorType(String factorType) {
        this.setFactorType(factorType);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withConstantType(String constantType) {
        this.setConstantType(constantType);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withConstantValue(String constantValue) {
        this.setConstantValue(constantValue);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withFactorScriptParam(String factorScriptParam) {
        this.setFactorScriptParam(factorScriptParam);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_factor")
    public RuleFactorDO withFactorScript(String factorScript) {
        this.setFactorScript(factorScript);
        return this;
    }
}