package com.jd.cho.rule.engine.dal.DO;

import com.jd.cho.rule.engine.common.base.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rule_def
 */
@Data
@ToString(callSuper = true)
@NoArgsConstructor
@SuperBuilder
@AllArgsConstructor
public class RuleDefDO extends BaseEntity {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   规则编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_code")
    private String ruleCode;

    /**
     * Database Column Remarks:
     *   规则名称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_name")
    private String ruleName;

    /**
     * Database Column Remarks:
     *   版本号
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.version")
    private Integer version;

    /**
     * Database Column Remarks:
     *   是否最新版本（0:否，1:是）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.latest")
    private Integer latest;

    /**
     * Database Column Remarks:
     *   优先级
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.priority")
    private Integer priority;

    /**
     * Database Column Remarks:
     *   备注
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.remark")
    private String remark;

    /**
     * Database Column Remarks:
     *   状态（0:否，1:是）
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.status")
    private Boolean status;

    /**
     * Database Column Remarks:
     *   是否删除 1-否，0-是
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.yn")
    private Boolean yn;

    /**
     * Database Column Remarks:
     *   规则条件
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_condition")
    private String ruleCondition;

    /**
     * Database Column Remarks:
     * 规则行为
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_def.rule_action")
    private String ruleAction;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleCode(String ruleCode) {
        this.setRuleCode(ruleCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleName(String ruleName) {
        this.setRuleName(ruleName);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withVersion(Integer version) {
        this.setVersion(version);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withLatest(Integer latest) {
        this.setLatest(latest);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withYn(Boolean yn) {
        this.setYn(yn);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleCondition(String ruleCondition) {
        this.setRuleCondition(ruleCondition);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_def")
    public RuleDefDO withRuleAction(String ruleAction) {
        this.setRuleAction(ruleAction);
        return this;
    }
}