package com.jd.cho.rule.engine.infr.gateway.impl.dal.DO;

import com.jd.cho.rule.engine.common.base.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rule_scene_action
 */
@Data
@ToString(callSuper = true)
@NoArgsConstructor
@SuperBuilder
@AllArgsConstructor
public class RuleSceneActionDO extends BaseEntity {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   场景编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.scene_code")
    private String sceneCode;

    /**
     * Database Column Remarks:
     *   行为编码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.action_code")
    private String actionCode;

    /**
     * Database Column Remarks:
     * 行为类型
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.action_type")
    private String actionType;

    /**
     * Database Column Remarks:
     * 是否删除 1-否，0-是
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.yn")
    private Boolean yn;

    /**
     * Database Column Remarks:
     * 行为内容
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: rule_scene_action.action")
    private String action;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withSceneCode(String sceneCode) {
        this.setSceneCode(sceneCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withActionCode(String actionCode) {
        this.setActionCode(actionCode);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withActionType(String actionType) {
        this.setActionType(actionType);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withYn(Boolean yn) {
        this.setYn(yn);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: rule_scene_action")
    public RuleSceneActionDO withAction(String action) {
        this.setAction(action);
        return this;
    }
}